{{ config(materialized='table') }}

WITH SUSHI_PLACES_DIMENSION AS (
SELECT p.ID,
       p.DISPLAYNAME_TEXT,
       s.ADDRESS,
       s.CITY,
       s.STATE,
       s.ZIP_CODE,
       s.BOROUGH,
       p.LOCATION_LATITUDE AS LATITUDE,
       p.LOCATION_LONGITUDE AS LONGITUDE,
       p.RATING AS OVERALL_RATING,
       p.USERRATINGCOUNT,
       p.PRICELEVEL,
       p.BUSINESSSTATUS,
       p.PRIMARYTYPEDISPLAYNAME_TEXT AS PRIMARY_TYPE,
       p.TAKEOUT,
       p.DELIVERY,
       p.DINEIN,
       p.RESERVABLE,
       p.SERVESBREAKFAST,
       p.SERVESLUNCH,
       p.SERVESDINNER,
       p.SERVESBRUNCH,
       p.SERVESDESSERT,
       p.SERVESVEGETARIANFOOD,
       p.SERVESCOFFEE,
       p.SERVESBEER,
       p.SERVESWINE,
       p.ACCESSIBILITYOPTIONS_WHEELCHAIRACCESSIBLEPARKING AS WHEELCHAIRACCESSIBLEPARKING,
       p.ACCESSIBILITYOPTIONS_WHEELCHAIRACCESSIBLEENTRANCE AS WHEELCHAIRACCESSIBLEENTRANCE,
       p.ACCESSIBILITYOPTIONS_WHEELCHAIRACCESSIBLERESTROOM AS WHEELCHAIRACCESSIBLERESTROOM,
       p.ACCESSIBILITYOPTIONS_WHEELCHAIRACCESSIBLESEATING AS WHEELCHAIRACCESSIBLESEATING,
       p.LIVEMUSIC,
       p.GOODFORCHILDREN,
       p.ALLOWSDOGS,
       p.RESTROOM,
       p.GOODFORWATCHINGSPORTS,
       p.MENUFORCHILDREN,
       CURRENT_DATE AS LOAD_DATE
FROM {{ source('raw_data_sources', 'RAW_SUSHI_PLACES') }} p
INNER JOIN {{ ref('std_sushi_places') }} s
ON p.ID = s.ID
)

SELECT *
FROM SUSHI_PLACES_DIMENSION