{{ config(materialized='view') }}

WITH REVIEW_DATA AS (
    SELECT REVIEW_ID,
    PLACE_ID,
    RATING,
    PUBLISHTIME,
    TEXT
    FROM SUSHI.NYC.SUSHI_PLACE_REVIEWS_FACT
),

V_ALL_REVIEW_INFO AS (
SELECT r.*,
       s.WORD_TOKENS,
FROM SUSHI.NYC.SUSHI_REVIEW_SENTIMENT_FACT s
INNER JOIN REVIEW_DATA r
ON s.REVIEW_ID = r.REVIEW_ID
)

SELECT *
FROM V_ALL_REVIEW_INFO