{{ config(materialized='view') }}

WITH V_AVG_SENTIMENT_SCORES AS (
SELECT AVG(VADER_COMPOUND) AS AVG_VADER_COMPOUND,
       AVG(VADER_NEG) AS AVG_VADER_NEG,
       AVG(VADER_NEU) AS AVG_VADER_NEU,
       AVG(VADER_POS) AS AVG_VADER_POS,
       AVG(BASE_NEG) AS AVG_BASE_NEG,
       AVG(BASE_NEU) AS AVG_BASE_NEU,
       AVG(BASE_POS) AS AVG_BASE_POS,
       AVG(FOODY_NEG) AS AVG_FOODY_NEG,
       AVG(FOODY_NEU) AS AVG_FOODY_NEU,
       AVG(FOODY_POS) AS AVG_FOODY_POS
       
FROM {{ source('scored_reviews', 'SUSHI_REVIEW_SENTIMENT_FACT') }}
)

SELECT *
FROM V_AVG_SENTIMENT_SCORES