{{ config(materialized='view') }}

WITH DIM_COLUMNS AS (
SELECT ID,
       DISPLAYNAME_TEXT,
       BOROUGH,
       ADDRESS,
       CITY,
       ZIP_CODE,
       PRICELEVEL,
       LATITUDE,
       LONGITUDE,
       OVERALL_RATING,
       USERRATINGCOUNT,
       PRIMARY_TYPE
FROM {{ ref("sushi_places_dimension") }}  SUSHI_PLACES_DIMENSION
),

PLACE_REVIEW_MAPPER AS (
SELECT DISTINCT PLACE_ID,
                REVIEW_ID
FROM {{ ref("sushi_place_reviews_fact") }}  SUSHI_PLACE_REVIEWS_FACT
),

AGG_SENTIMENTS AS (
SELECT  m.PLACE_ID,//s.REVIEW_ID,
        AVG(s.VADER_NEG) AS AVG_VADER_NEG,
        AVG(s.VADER_NEU) AS AVG_VADER_NEU,
        AVG(s.VADER_POS) AS AVG_VADER_POS,
        AVG(s.VADER_COMPOUND) AS AVG_VADER_COMPOUND,
        AVG(s.BASE_NEG) AS AVG_BASE_NEG,
        AVG(s.BASE_NEU) AS AVG_BASE_NEU,
        AVG(s.BASE_POS) AS AVG_BASE_POS,
        AVG(s.FOODY_NEG) AS AVG_FOODY_NEG,
        AVG(s.FOODY_NEU) AS AVG_FOODY_NEU,
        AVG(s.FOODY_POS) AS AVG_FOODY_POS,
        AVG(s.TEXTBLOB_POLARITY) AS AVG_TEXTBLOB_POLARITY,
        AVG(s.TEXTBLOB_SUBJECTIVITY) AS AVG_TEXTBLOB_SUBJECTIVITY
FROM {{ source('scored_reviews', 'SUSHI_REVIEW_SENTIMENT_FACT') }} s
INNER JOIN PLACE_REVIEW_MAPPER m
ON s.review_id = m.review_id
GROUP BY PLACE_ID
),

V_SENTIMENT_METRICS_BY_LOCATION AS (
SELECT d.ID,
       d.DISPLAYNAME_TEXT,
       d.BOROUGH,
       d.ADDRESS,
       d.CITY,
       d.ZIP_CODE,
       d.PRICELEVEL,
       d.LATITUDE,
       d.LONGITUDE,
       d.OVERALL_RATING,
       d.USERRATINGCOUNT,
       d.PRIMARY_TYPE,
       s.*
FROM DIM_COLUMNS d
INNER JOIN AGG_SENTIMENTS s
ON d.ID = s.PLACE_ID
)

SELECT * FROM V_SENTIMENT_METRICS_BY_LOCATION